sudo: false
language: cpp
compiler:
  - gcc
  - clang
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
  - ctest -D ExperimentalBuild
  - ctest -D ExperimentalMemCheck
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - gcc-4.7
            - g++-4.7
            - valgrind
            - cmake
